export const data = [
  { id: 1, kodam: "Naga Terbang" },
  { id: 2, kodam: "Angsa Gowak" },
  { id: 3, kodam: "Kipas Neyeng" },
  { id: 4, kodam: "Kucing Lucu" },
  { id: 5, kodam: "Anjing Setia" },
  { id: 6, kodam: "Gajah Besar" },
  { id: 7, kodam: "Harimau Ganas" },
  { id: 8, kodam: "Burung Hantu" },
  { id: 9, kodam: "Ikan Mas" },
  { id: 10, kodam: "Kuda Poni" },
  { id: 11, kodam: "Bebek Kuning" },
  { id: 12, kodam: "Kelinci Imut" },
  { id: 13, kodam: "Singa Raja" },
  { id: 14, kodam: "Kupu-Kupu" },
  { id: 15, kodam: "Lumba-Lumba" },
  { id: 16, kodam: "Panda Gemuk" },
  { id: 17, kodam: "Ular Sanca" },
  { id: 18, kodam: "Kura-Kura" },
  { id: 19, kodam: "Kambing Gunung" },
  { id: 20, kodam: "Rusa Lincah" },
  { id: 21, kodam: "Banteng Kuat" },
  { id: 22, kodam: "Kucing Hutan" },
  { id: 23, kodam: "Burung Merak" },
  { id: 24, kodam: "Kuda Laut" },
  { id: 25, kodam: "Gorila Besar" },
  { id: 26, kodam: "Kucing Persia" },
  { id: 27, kodam: "Anjing Bulldog" },
  { id: 28, kodam: "Kucing Anggora" },
  { id: 29, kodam: "Burung Elang" },
  { id: 30, kodam: "Ikan Hiu" },
  { id: 31, kodam: "Kuda Zebra" },
  { id: 32, kodam: "Kucing Siam" },
  { id: 33, kodam: "Anjing Husky" },
  { id: 34, kodam: "Burung Kakak Tua" },
  { id: 35, kodam: "Ikan Paus" },
  { id: 36, kodam: "Kuda Nil" },
  { id: 37, kodam: "Kucing Bengal" },
  { id: 38, kodam: "Anjing Poodle" },
  { id: 39, kodam: "Burung Kenari" },
  { id: 40, kodam: "Ikan Pari" },
  { id: 41, kodam: "Kuda Coklat" },
  { id: 42, kodam: "Kucing Maine Coon" },
  { id: 43, kodam: "Anjing Dalmatian" },
  { id: 44, kodam: "Burung Beo" },
  { id: 45, kodam: "Ikan Koi" },
  { id: 46, kodam: "Kuda Putih" },
  { id: 47, kodam: "Kucing Sphynx" },
  { id: 48, kodam: "Anjing Chihuahua" },
  { id: 49, kodam: "Burung Kolibri" },
  { id: 50, kodam: "Ikan Lele" },
  { id: 51, kodam: "Kuda Hitam" },
  { id: 52, kodam: "Kucing Scottish Fold" },
  { id: 53, kodam: "Anjing Shih Tzu" },
  { id: 54, kodam: "Burung Jalak" },
  { id: 55, kodam: "Ikan Cupang" },
  { id: 56, kodam: "Kuda Arab" },
  { id: 57, kodam: "Kucing Ragdoll" },
  { id: 58, kodam: "Anjing Golden Retriever" },
  { id: 59, kodam: "Burung Cendrawasih" },
  { id: 60, kodam: "Ikan Gurame" },
  { id: 61, kodam: "Kuda Mustang" },
  { id: 62, kodam: "Kucing British Shorthair" },
  { id: 63, kodam: "Anjing Labrador" },
  { id: 64, kodam: "Burung Merpati" },
  { id: 65, kodam: "Ikan Salmon" },
  { id: 66, kodam: "Kuda Andalusia" },
  { id: 67, kodam: "Kucing Abyssinian" },
  { id: 68, kodam: "Anjing Beagle" },
  { id: 69, kodam: "Burung Puyuh" },
  { id: 70, kodam: "Ikan Tuna" },
  { id: 71, kodam: "Kuda Fjord" },
  { id: 72, kodam: "Kucing Birman" },
  { id: 73, kodam: "Anjing Boxer" },
  { id: 74, kodam: "Burung Pipit" },
  { id: 75, kodam: "Ikan Kakap" },
  { id: 76, kodam: "Kuda Friesian" },
  { id: 77, kodam: "Kucing Chartreux" },
  { id: 78, kodam: "Anjing Cocker Spaniel" },
  { id: 79, kodam: "Burung Gereja" },
  { id: 80, kodam: "Ikan Barakuda" },
  { id: 81, kodam: "Kuda Haflinger" },
  { id: 82, kodam: "Kucing Devon Rex" },
  { id: 83, kodam: "Anjing Dachshund" },
  { id: 84, kodam: "Burung Kutilang" },
  { id: 85, kodam: "Ikan Belut" },
  { id: 86, kodam: "Kuda Lipizzan" },
  { id: 87, kodam: "Kucing Exotic Shorthair" },
  { id: 88, kodam: "Anjing Doberman" },
  { id: 89, kodam: "Burung Kakatua" },
  { id: 90, kodam: "Ikan Nila" },
  { id: 91, kodam: "Kuda Morgan" },
  { id: 92, kodam: "Kucing Havana Brown" },
  { id: 93, kodam: "Anjing Greyhound" },
  { id: 94, kodam: "Burung Lovebird" },
  { id: 95, kodam: "Ikan Mujair" },
  { id: 96, kodam: "Kuda Palomino" },
  { id: 97, kodam: "Kucing Korat" },
  { id: 98, kodam: "Anjing Maltese" },
  { id: 99, kodam: "Burung Parkit" },
  { id: 100, kodam: "Ikan Patin" },
  { id: 101, kodam: "Kuda Paso Fino" },
  { id: 102, kodam: "Kucing LaPerm" },
  { id: 103, kodam: "Anjing Pomeranian" },
  { id: 104, kodam: "Burung Pelikan" },
  { id: 105, kodam: "Ikan Sarden" },
  { id: 106, kodam: "Kuda Percheron" },
  { id: 107, kodam: "Kucing Manx" },
  { id: 108, kodam: "Anjing Pug" },
  { id: 109, kodam: "Burung Rajawali" },
  { id: 110, kodam: "Ikan Tenggiri" },
  { id: 111, kodam: "Kuda Quarter" },
  { id: 112, kodam: "Kucing Munchkin" },
  { id: 113, kodam: "Anjing Rottweiler" },
  { id: 114, kodam: "Burung Robin" },
  { id: 115, kodam: "Ikan Tongkol" },
  { id: 116, kodam: "Kuda Shire" },
  { id: 117, kodam: "Kucing Ocicat" },
  { id: 118, kodam: "Anjing Samoyed" },
  { id: 119, kodam: "Burung Srigunting" },
  { id: 120, kodam: "Ikan Teri" },
  { id: 121, kodam: "Kuda Suffolk" },
  { id: 122, kodam: "Kucing Oriental" },
  { id: 123, kodam: "Anjing Schnauzer" },
  { id: 124, kodam: "Burung Tekukur" },
  { id: 125, kodam: "Ikan Toman" },
  { id: 126, kodam: "Kuda Tennessee Walker" },
  { id: 127, kodam: "Kucing Persian" },
  { id: 128, kodam: "Anjing Shar Pei" },
  { id: 129, kodam: "Burung Trucuk" },
  { id: 130, kodam: "Ikan Tuna Sirip Kuning" },
  { id: 131, kodam: "Kuda Thoroughbred" },
  { id: 132, kodam: "Kucing Pixie Bob" },
  { id: 133, kodam: "Anjing Siberian Husky" },
  { id: 134, kodam: "Burung Walet" },
  { id: 135, kodam: "Ikan Wader" },
  { id: 136, kodam: "Kuda Trakehner" },
  { id: 137, kodam: "Kucing Ragamuffin" },
  { id: 138, kodam: "Anjing Staffordshire Bull Terrier" },
  { id: 139, kodam: "Burung Wambi" },
  { id: 140, kodam: "Ikan   Betutu" },
  { id: 141, kodam: "Kuda Welsh" },
  { id: 142, kodam: "Kucing Russian Blue" },
  { id: 143, kodam: "Anjing Weimaraner" },
  { id: 144, kodam: "Burung Zebra Finch" },
  { id: 145, kodam: "Ikan Arwana" },
  { id: 146, kodam: "Kuda Appaloosa" },
  { id: 147, kodam: "Kucing Savannah" },
  { id: 148, kodam: "Anjing West Highland White Terrier" },
  { id: 149, kodam: "Burung Anis" },
  { id: 150, kodam: "Ikan Betutu" },
  { id: 151, kodam: "Kuda Akhal-Teke" },
  { id: 152, kodam: "Kucing Selkirk Rex" },
  { id: 153, kodam: "Anjing Whippet" },
  { id: 154, kodam: "Burung Anis Merah" },
  { id: 155, kodam: "Ikan Buntal" },
  { id: 156, kodam: "Kuda American Paint" },
  { id: 157, kodam: "Kucing Siamese" },
  { id: 158, kodam: "Anjing Yorkshire Terrier" },
  { id: 159, kodam: "Burung Anis Kembang" },
  { id: 160, kodam: "Ikan Cupang Hias" },
  { id: 161, kodam: "Kuda American Quarter" },
  { id: 162, kodam: "Kucing Singapura" },
  { id: 163, kodam: "Anjing Akita" },
  { id: 164, kodam: "Burung Anis Cendana" },
  { id: 165, kodam: "Ikan Discus" },
  { id: 166, kodam: "Kuda American Saddlebred" },
  { id: 167, kodam: "Kucing Snowshoe" },
  { id: 168, kodam: "Anjing Alaskan Malamute" },
  { id: 169, kodam: "Burung Anis Macan" },
  { id: 170, kodam: "Ikan Gabus" },
  { id: 171, kodam: "Kuda American Standardbred" },
  { id: 172, kodam: "Kucing Somali" },
  { id: 173, kodam: "Anjing Australian Shepherd" },
  { id: 174, kodam: "Burung Anis Kembang" },
  { id: 175, kodam: "Ikan Guppy" },
  { id: 176, kodam: "Kuda American Warmblood" },
  { id: 177, kodam: "Kucing Sphynx" },
  { id: 178, kodam: "Anjing Basenji" },
  { id: 179, kodam: "Burung Anis Merah" },
  { id: 180, kodam: "Ikan Kerapu" },
  { id: 181, kodam: "Kuda Andalusian" },
  { id: 182, kodam: "Kucing Tonkinese" },
  { id: 183, kodam: "Anjing Basset Hound" },
  { id: 184, kodam: "Burung Anis Kembang" },
  { id: 185, kodam: "Ikan Koi" },
  { id: 186, kodam: "Kuda Anglo-Arabian" },
  { id: 187, kodam: "Kucing Turkish Angora" },
  { id: 188, kodam: "Anjing Beagle" },
  { id: 189, kodam: "Burung Anis Macan" },
  { id: 190, kodam: "Ikan Louhan" },
  { id: 191, kodam: "Kuda Arabian" },
  { id: 192, kodam: "Kucing Turkish Van" },
  { id: 193, kodam: "Anjing Belgian Malinois" },
  { id: 194, kodam: "Burung Anis Kembang" },
  { id: 195, kodam: "Ikan Molly" },
  { id: 196, kodam: "Kuda Ardennes" },
  { id: 197, kodam: "Kucing Ural Rex" },
  { id: 198, kodam: "Anjing Bernese Mountain Dog" },
  { id: 199, kodam: "Burung Anis Merah" },
  { id: 200, kodam: "Ikan Molly" },
  { id: 201, kodam: "Kuda Australian Stock" },
  { id: 202, kodam: "Kucing York Chocolate" },
  { id: 203, kodam: "Anjing Bichon Frise" },
  { id: 204, kodam: "Burung Anis Kembang" },
  { id: 205, kodam: "Ikan Neon Tetra" },
  { id: 206, kodam: "Kuda Azteca" },
  { id: 207, kodam: "Kucing Bengal" },
  { id: 208, kodam: "Anjing Bloodhound" },
  { id: 209, kodam: "Burung Anis Macan" },
  { id: 210, kodam: "Ikan Oscar" },
  { id: 211, kodam: "Kuda Barb" },
  { id: 212, kodam: "Kucing Birman" },
  { id: 213, kodam: "Anjing Border Collie" },
  { id: 214, kodam: "Burung Anis Kembang" },
  { id: 215, kodam: "Ikan Platy" },
  { id: 216, kodam: "Kuda Bashkir" },
  { id: 217, kodam: "Kucing Bombay" },
  { id: 218, kodam: "Anjing Boston Terrier" },
  { id: 219, kodam: "Burung Anis Merah" },
  { id: 220, kodam: "Ikan Rainbow" },
  { id: 221, kodam: "Kuda Belgian" },
  { id: 222, kodam: "Kucing British Shorthair" },
  { id: 223, kodam: "Anjing Boxer" },
  { id: 224, kodam: "Burung Anis Kembang" },
  { id: 225, kodam: "Ikan Red Devil" },
  { id: 226, kodam: "Kuda Black Forest" },
  { id: 227, kodam: "Kucing Burmese" },
  { id: 228, kodam: "Anjing Bull Terrier" },
  { id: 229, kodam: "Burung Anis Macan" },
  { id: 230, kodam: "Ikan Swordtail" },
  { id: 231, kodam: "Kuda Brumby" },
  { id: 232, kodam: "Kucing Chartreux" },
  { id: 233, kodam: "Anjing Bulldog" },
  { id: 234, kodam: "Burung Anis Kembang" },
  { id: 235, kodam: "Ikan Tetra" },
  { id: 236, kodam: "Kuda Clydesdale" },
  { id: 237, kodam: "Kucing Cornish Rex" },
  { id: 238, kodam: "Anjing Bullmastiff" },
  { id: 239, kodam: "Burung Anis Merah" },
  { id: 240, kodam: "Ikan Tiger Barb" },
  { id: 241, kodam: "Kuda Criollo" },
  { id: 242, kodam: "Kucing Cymric" },
  { id: 243, kodam: "Anjing Cairn Terrier" },
  { id: 244, kodam: "Burung Anis Kembang" },
  { id: 245, kodam: "Ikan Zebra Danio" },
  { id: 246, kodam: "Kuda Curly" },
  { id: 247, kodam: "Kucing Devon Rex" },
  { id: 248, kodam: "Anjing Cavalier King Charles Spaniel" },
  { id: 249, kodam: "Burung Anis Macan" },
  { id: 250, kodam: "Ikan Angelfish" },
  { id: 251, kodam: "Kuda Dales" },
  { id: 252, kodam: "Kucing Egyptian Mau" },
  { id: 253, kodam: "Anjing Chihuahua" },
  { id: 254, kodam: "Burung Anis Kembang" },
  { id: 255, kodam: "Ikan Betta" },
  { id: 256, kodam: "Kuda Dartmoor" },
  { id: 257, kodam: "Kucing European Shorthair" },
  { id: 258, kodam: "Anjing Chinese Crested" },
  { id: 259, kodam: "Burung Anis Merah" },
  { id: 260, kodam: "Ikan Corydoras" },
  { id: 261, kodam: "Kuda Dutch Warmblood" },
  { id: 262, kodam: "Kucing Exotic Shorthair" },
  { id: 263, kodam: "Anjing Chow Chow" },
  { id: 264, kodam: "Burung Anis Kembang" },
  { id: 265, kodam: "Ikan Discus" },
  { id: 266, kodam: "Kuda Falabella" },
  { id: 267, kodam: "Kucing Havana Brown" },
  { id: 268, kodam: "Anjing Dalmatian" },
  { id: 269, kodam: "Burung Anis Macan" },
  { id: 270, kodam: "Ikan Guppy" },
  { id: 271, kodam: "Kuda Fjord" },
  { id: 272, kodam: "Kucing Himalayan" },
  { id: 273, kodam: "Anjing Dandie Dinmont Terrier" },
  { id: 274, kodam: "Burung Anis Kembang" },
  { id: 275, kodam: "Ikan Molly" },
  { id: 276, kodam: "Kuda Friesian" },
  { id: 277, kodam: "Kucing Japanese Bobtail" },
  { id: 278, kodam: "Anjing Doberman Pinscher" },
];
